 version: '3' 

 services:
   nginx:
     image: arm64v8/nginx:alpine
     container_name: webserver
     volumes:
       - ./web:/var/www/html
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
     ports:
       - "7080:80"
     depends_on:
       - php

   php:
     image: arm64v8/php:fpm-alpine
     #image: arm64v8/php:7.4-alpine
     container_name: php-fpm
     volumes:
       - ./web:/var/www/html
     depends_on:
       - mariadb

   mariadb:
     image: arm64v8/mariadb:10.5
     container_name: mariadb
     environment:
       MYSQL_ROOT_PASSWORD: root_toor
       MYSQL_DATABASE: mysql
       MYSQL_USER: user
       MYSQL_PASSWORD: user_resu
     ports:
       - "3307:3306"  # Ganti port dari 3306 ke 3307

   phpmyadmin:
     image: arm64v8/phpmyadmin:latest
     environment:
       PMA_HOST: mariadb
       MYSQL_ROOT_PASSWORD: root_password
       MYSQL_USER: user
       MYSQL_PASSWORD: user_password
     ports:
       - "7081:80"
     depends_on:
       - mariadb
